### PR TITLE
Journal week 3

### PR DESCRIPTION
**Pull request by boshnivolo**

### CODE REVIEW

**Comment by karjac14** [comment]
Great start Jasmine! nine more weeks to go. :+1:

**Comment by ericquayson** [comment]
Good journal Jasmine. I agree with you on the point of sharing resources via slack and slowly molding the perfect career after this program. We are all in this together.  :+1:

**Comment by jmcreasman** [comment]
Your positive outlook is refreshing. Just keep swimming! :+1:

**Comment by jeremyrist** [comment]
:+1: I like the tutorial! Thanks for the links... and how about if the homies could get an example of a good "user story"? If I had any Hot Pockets around right now I would be falling in 'em haha

**Comment by ShayHall** [comment]
That cat lives in my feels right now.  Thanks for that.  I think you have a good start on your tutorial.  Maybe flesh it out a bit.  :cat: :cat2:

**Comment by cmauban** [comment]
Yes, I definitely agree- we are all growing together day by day! Nice read :+1:

**Comment by nickycadavillo** [comment]
:+1: Your final journal is great.  I definitely feel like our slack has become a great resource;  it's good we're swimming together!   I especially liked the cat gif; couldn't be more true!

**Pull request merged**
